### ISSUE TITLE
ICC: Putricide Trap [Heroic]

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#40] opened 2020-02-04 19:37 UTC
https://github.com/azerothcore/azerothcore-wotlk/issues/2568

**Comment by kjack9** [comment] 2023-09-19 23:17
I know this report is old, but its actually still applicable. The issue is that only CREATURES have the necessary data attached to have their damage scaled appropriately. That means that damage caused by anything that is not a creature (like the world or traps that aren't owned by their caster) is not adjusted correctly.

I will be working on some updates in the near future to better handle this. As such, marking this issue as WIP.

**Comment by kjack9** [comment] 2023-09-30 17:34
So, I was wrong - this isn't a world damage issue, it's far more interesting than that.

This image is from the linked bug report:
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/d52d8b87-7403-484e-9058-f3fe4ea5c3da)

When the combat log says "Putricide's Trap", it's not actually a game object! "Putricide's Trap" is a level 1 invisible infernal trigger creature that is standing in the middle of the hall.

![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/a39ceddf-15f7-44af-ad4c-e83877b29255)

In fact, Blizzard often uses invisible creatures to accomplish seemingly-world-based effects. The problem in this case is that the creature is level 1... which AutoBalance happily scales up to your level, causing it to do massive damage.

Further compounding the problem is that the `HandlePeriodicDamageAurasTick` hook is interpreting the damage wrong. The short story is that `HandlePeriodicDamageAurasTick` thinks that "5% of max player health" is actually "5 damage". So i this case AutoBalance is scaling 5 "damage" up to the appropriate damage for a level 80 creature (let's say 150 "damage"), which is then applied as 150 **percent** of your health. The result is that you get hit for more than 100% of your total health and you die.

This issue will be fixed in two parts:
- first, an upcoming AutoBalance release will correctly identify trigger creatures that shouldn't be scaled and will leave them their starting level. It will then scale the damage appropriately given the number of players in the instance.
- second is a bug fix PR for AzerothCore (https://github.com/azerothcore/azerothcore-wotlk/pull/17387/files) that will fix the `HandlePeriodicDamageAurasTick` hook to always receive (and alter) the final damage value and not a percentage.

Still on track to get this resolved, just has a few more moving pieces than you'd think.

**Comment by kjack9** [comment] 2023-10-11 07:40
https://github.com/azerothcore/azerothcore-wotlk/pull/17387/ was merged. My part of this fix is coming Very Soon.

**Closed** 2023-10-19 15:52 UTC
Labels: bug, WIP - To be completed
