### ISSUE TITLE
Trial of the crusader: faction champions' stats are not scaled down

### ISSUE THREAD

**Issue by WangDianhui** [azerothcore/mod-autobalance#144] opened 2023-08-03 03:09 UTC
### Describe your feature request or suggestion in detail

If there are characters whose reputation with Argent Crusade is friendly or more in the instance, the faction champions' stats would not be scaled.
<img width="400" alt="Neutral with Argent Crusade" src="https://github.com/azerothcore/mod-autobalance/assets/124812590/1d6ec147-6fed-4717-9648-e05e615e87b5">
<img width="400" alt="Friendly with Argent Crusade" src="https://github.com/azerothcore/mod-autobalance/assets/124812590/2e1ba9ba-a67e-4c5c-aa50-f9bf9a210ee2">

**Comment by pangolp** [comment] 2023-08-03 07:07
How strange that he does not climb with the champions ...
I haven't really used this module, it has many configurations...
I'll have to try it.

**Comment by cdenq** [comment] 2023-08-15 20:07
Is your party cross-faction by any change? Scaling will apply properly if everyone is the same faction.

**Comment by kjack9** [comment] 2023-09-20 05:23
I want to wait until #155 is merged and then troubleshoot this if its still happening - that will give us some more detail via the `.ab mapstat` and `.ab creaturestat` commands.

**Comment by WangDianhui** [comment] 2023-09-21 02:04
This problem still exists. I have already pulled the latest commit for both server and mod.
![1](https://github.com/azerothcore/mod-autobalance/assets/124812590/d87ddc63-bf0f-4173-bf3d-a4d9e3880998)
![2](https://github.com/azerothcore/mod-autobalance/assets/124812590/fd46c712-2199-49bf-b1bc-de723481fcbf)
![3](https://github.com/azerothcore/mod-autobalance/assets/124812590/47bf0318-f58e-4dd6-851b-b3754077d9ae)
The champions' HP does not change as the num of players changes.

**Comment by WangDianhui** [comment] 2023-09-21 02:14
I think I've found the problem...
<img width="682" alt="4" src="https://github.com/azerothcore/mod-autobalance/assets/124812590/11f608a9-d0e5-480d-abcd-a3b0b72ace11">
If the party leader's name contains chinese characters, the champions' stats would not be changed. But for English names, the mod works properly.

**Comment by kjack9** [comment] 2023-09-21 15:06
Wow, I have no idea what could possibly be causing that. The mod doesn't care about character names for making decisions. It DOES have character names in some of the announcements, but I can't think of why that would matter.
I don't even know where to begin on troubleshooting this.

Marking "Help Wanted" for now.

**Comment by WangDianhui** [comment] 2023-09-23 11:41
I've confirmed that the problem is independence with the name. But it just occurred when there are some SPECIFIC characters in the instance, no matter who the party leader is.

I'm still looking for the trigger condition.

**Comment by WangDianhui** [comment] 2023-09-23 12:15
Confirmed. If there are characters whose reputation with Argent Crusade is friendly or more in the instance, the faction champions' stats would not be scaled.
<img width="400" alt="Neutral with Argent Crusade" src="https://github.com/azerothcore/mod-autobalance/assets/124812590/1d6ec147-6fed-4717-9648-e05e615e87b5">
<img width="400" alt="Friendly with Argent Crusade" src="https://github.com/azerothcore/mod-autobalance/assets/124812590/2e1ba9ba-a67e-4c5c-aa50-f9bf9a210ee2">

**Comment by kjack9** [comment] 2023-10-12 18:12
I've added this to my personal backlog.

**Comment by kjack9** [comment] 2023-10-19 16:52
@WangDianhui can you please test with the latest version of AC and AutoBalance and let me know if the issue is still happening?

**Comment by WangDianhui** [comment] 2023-10-21 03:10
> @WangDianhui can you please test with the latest version of AC and AutoBalance and let me know if the issue is still happening?

Tested, the problem has gone. Champions' scaling are now irrelevant with reputation.

**Comment by kjack9** [comment] 2023-10-21 03:12
> > @WangDianhui can you please test with the latest version of AC and AutoBalance and let me know if the issue is still happening?
> 
> Tested, the problem has gone. Champions' scaling are now irrelevant with reputation.

Great! Closing as confirmed fixed by #157

**Closed by kjack9** 2023-10-21 03:12 UTC
Labels: bug, not confirmed
