### ISSUE TITLE
Feature: Scaling for critters that spawn, like plagued insects in Stratholme

### ISSUE THREAD

**Issue by sabrinajestar** [azerothcore/mod-autobalance#165] opened 2023-10-28 16:51 UTC
### Describe your feature request or suggestion in detail

Insects, rats, grubs, etc, that spawn between the gates or from supply crates are not scaling their damage or hp to solo level, making these parts of the instance very challenging or impossible to solo.

**Comment by kjack9** [comment] 2023-10-28 17:13
Are you on the latest revision of AutoBalance? This should be fixed with the most recent updates.

If you are and you're still seeing this issue, please provide the following while targeting the problem creature:
- `.ab mapstat`
- `.ab creaturestat`

Screenshots work fine. Thanks!

**Comment by icemansparks** [comment] 2023-10-28 19:16
We had the same problem today in Razorfen Downs where the first Boss is an event with creatures that spawn after the instance is loaded based on the event.
The second wave (4 elites) was not doable with two people as the mobs just obliterated us :D

We were using the commit 50a5d5e from last week, a test with the changes from a newer commit can probably be done tomorrow i think 🤔

**Comment by kjack9** [comment] 2023-10-28 21:08
I'll check on this tonight. If either of you could upload your `AutoBalance.conf` file to this issue that would be very helpful.

**Comment by sabrinajestar** [comment] 2023-10-28 21:30
Yes - thank you! (I've also encountered the issue in Razorfen Downs).

I haven't done a rebuild in a while but will certainly if it could help.

[AutoBalance.conf.txt](https://github.com/azerothcore/mod-autobalance/files/13196751/AutoBalance.conf.txt)

**Comment by kjack9** [comment] 2023-10-28 21:43
> Yes - thank you! (I've also encountered the issue in Razorfen Downs).
> 
> I haven't done a rebuild in a while but will certainly if it could help.
> 
> [AutoBalance.conf.txt](https://github.com/azerothcore/mod-autobalance/files/13196751/AutoBalance.conf.txt)

Definitely update. The version that got pushed last week totally redid the exact functionality you're talking about.

**Comment by kjack9** [comment] 2023-10-29 06:51
@sabrinajestar 

I loaded up your provided config file and here are the results I get:

Plagued Rats in the Strath traps:
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/3babc56e-10ce-4a1a-8abb-bdb830ca070e)

Plagued Insect from the Strath supply boxes:
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/eecf5112-9788-4a7f-b7e1-d248646aaef8)

If your AutoBalance is older than about a week ago, neither of these cases would have been handled well. Please update and let me know if that resolves the issue for you.

**Comment by kjack9** [comment] 2023-10-29 07:04
> We had the same problem today in Razorfen Downs where the first Boss is an event with creatures that spawn after the instance is loaded based on the event. The second wave (4 elites) was not doable with two people as the mobs just obliterated us :D
> 
> We were using the commit [50a5d5e](https://github.com/azerothcore/mod-autobalance/commit/50a5d5e451d67cf5eb48a1d55bb1acec5aa5ef4a) from last week, a test with the changes from a newer commit can probably be done tomorrow i think 🤔

That commit should be new enough, but I can't replicate the issue you're having.

![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/64ace4d4-8629-486a-97e6-7ee95c1ef98d)
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/43e8df85-4c1d-4439-a013-604b107dd823)
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/0b762f22-a4ff-4810-8605-1369105843e0)
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/a999b6fe-6147-440b-8539-abf0d5ead32c)
![image](https://github.com/azerothcore/mod-autobalance/assets/19712078/e9cdc9c7-e3df-4abb-be4c-f9d1359a6a45)

If you've updated to the latest version of AutoBalance, please open a new Issue of type Bug with the requested information and I'll be glad to look closer. I'll need your AutoBalance.conf too, please.

**Comment by kjack9** [comment] 2023-10-29 07:05
Can't be reproduced on the latest AutoBalance with the supplied conf file. Please re-open if you are still seeing this on the latest AutoBalance.

**Closed by kjack9** 2023-10-29 07:04 UTC
Labels: bug, not confirmed

**Comment by sabrinajestar** [comment] 2023-10-30 00:58
Thank you for looking into this! I updated and rebuilt my server and indeed am no longer seeing this issue.

**Comment by icemansparks** [comment] 2023-10-30 07:55
I updated to the commit https://github.com/azerothcore/mod-autobalance/commit/a20143dde5f6e1dd992f537f45be3b03dceaee76 as well as the latest azerothcore build - after rebuilding and updating the config file, the issue seems to be gone in Razorfen Downs - Summoned creatures had the correct adjusted health and damage values.
